### ISSUE TITLE
Column position aware imports

### ISSUE THREAD

**Issue by drumcircle** [exasol/cloud-storage-extension#129]
AVRO is a self-describing file format, column names and data types are well described in the schema.

The current behavior expects:

- Insert table to pre-exist
- Number of columns to match
- Order of the columns to match

Each of these expectations is limiting, are they necessary?

What about providing these run-time options?

- Create table if it does not exist
- Correlate data insertion to column names (if self-described in source)

The benefit would be less brittle, client-code, more robust insert.  Aside from 1 introspection query per insert, should not be large overhead.

**Comment by morazow** [comment]
Hello @drumcircle,

Thanks for the feedback! These are all nice suggestions.

Unfortunately, at the moment, it is not possible to run DDL queries from the `cloud-storage-extension`. The main reason is because they are implemented using user-defined functions. Exasol Import & Export UDF does not allow data definition / manipulation queries.

**Comment by drumcircle** [comment]
So UDF context would not give you a handle to the database metadata to check data types and column positions for a table?

**Comment by morazow** [comment]
Hello @drumcircle,

Yes, that is correct. At the moment, it is not possible to have that handle. This because we already [generate a SQL query](https://github.com/exasol/cloud-storage-extension/blob/main/src/main/scala/com/exasol/cloudetl/scriptclasses/FilesImportQueryGenerator.scala#L35-L46), that is run in one transaction for the whole parallel import.

But, it is not that all hope is lost. We can obtain table metadata (table name should be provided by user as a parameter) while generating above query and provide columns to the UDF scripts. We can again think about it in the future.

**Comment by drumcircle** [comment]
Absolutely correct.  The process has a bunch of overhead (spin-up, pre-processing) so another query in the beginning will have negligible performance impact.  The implications of being able to load into an evolving schema are significant.  Currently, the design practically forces you to create table, land data, merge to master, delete staging table.  Thanks again.

**Comment by drumcircle** [comment]
Wondering if this will be a priority in the coming weeks or months?  Thank you so much!

**Comment by morazow** [comment]
Hello @drumcircle,
Sorry, somehow missed your comment.
Unfortunately, we are not going to work on it in the near future. Thanks for your understanding.

**Comment by nicornk** [comment]
hey @morazow, first of all, thanks for the `cloud-storage-extension`. great work! 
We would also like to avoid the overhead of manually creating DDLs for creating the table where we land our parquet files. Since the parquet files are self-describing with a schema, couldn't `cloud-storage-extension` just generate the CREATE table and run it before the IMPORT?
Thanks!

**Comment by redcatbear** [comment]
Shelved because not in roadmap focus.
