### ISSUE TITLE
Ignore Error/Log Error

### ISSUE THREAD

**Issue by drumcircle** [exasol/cloud-storage-extension#61]
I would like to use DECIMAL(10,3) data type but load fails because of a single malformed input record that I can't identify.  Changing datatype to DOUBLE forces rounding and uses extra space.  Even better would be a validation/casting function to coerce a failed numeric casting or truncate long text values, on fail.  This would probably be expensive...

Would it make sense to have an ignore error flag with logging options to identify failure rows?  Log import errors seems part of the CSV loader, is it here also?

**Comment by morazow** [comment]
Hello @drumcircle,

Thanks for the feedback!

Yes, this is different than the loader, and unfortunately there is no any logs files created with erroneous rows. Both generating log file with erroneous rows and validation would be good features; however, currently, I am not sure how to include it.

But, in order to detect the malformed input, I can suggest the following steps:
- Open a remote logging, for example, on the Exasol management node. You can read about it [here](https://github.com/exasol/hadoop-etl-udfs/blob/master/doc/import.md#debugging).
- Similarly, set the log address in SQL session, `ALTER SESSION SET SCRIPT_OUTPUT_ADDRESS='10.0.0.10:3000';`
- You can see on the management node, which files or rows have failed.
- Optionally you can add more log lines to the code. For example, [line28](https://github.com/exasol/cloud-storage-etl-udfs/blob/master/src/main/scala/com/exasol/cloudetl/scriptclasses/ImportFiles.scala#L28) to log the files and [line49](https://github.com/exasol/cloud-storage-etl-udfs/blob/master/src/main/scala/com/exasol/cloudetl/scriptclasses/ImportFiles.scala#L49) to log the each imported row. 

However, please feel free to reach out, then we can look into the issue in a call together.

**Comment by morazow** [comment]
Hello @drumcircle,

I am going to close this issue. Please feel free to open a new issue if there are more questions.
