### ISSUE TITLE
Regex path matching

### ISSUE THREAD

**Issue by drumcircle** [exasol/cloud-storage-extension#65]
Question: is it possible to support regex path matching (not a simple prefix)?

` /<bucket>/<folder…>/<batch…>/<table>/<file>`

For small batch processing, it is useful to provide this prefix to get all data for a table in a batch.

` /<bucket>/<folder…>/<batch…>/<table>`

Another folder structure may be:

` /<bucket>/<folder…>/<table>/<batch…>/<file>`

For large batch processing, it is useful to organize folders this way to allow getting all data for a table across batches

` /<bucket>/<folder…>/<table>/<batch…>`

Assuming that AWS does not allow prefix wildcards, perhaps this is something that you could implement as a work-around.

I would like to store parquet files with paths like this: 

` /<bucket>/<folder…>/<batch…>/<table>/<file>`

But if I need to do a full sweep of all batches, supply you a path like this:

` /<bucket>/<folder…>/*/<table>`

In this case “%” or “*” matches any path until <table> is reached.  Maybe a regex expression would work well.

**Comment by morazow** [comment]
Hello @drumcircle ,

Thanks for the question! 

The current implementation uses the Hadoop FileSystem [`globStatus`](https://hadoop.apache.org/docs/r2.8.2/api/org/apache/hadoop/fs/FileSystem.html#globStatus(org.apache.hadoop.fs.Path)) method in order to list the files. So, it should support regex matching.

For example, to read some date partitioned tables, you can provide a string path with regex: 
```
"/bucket/{date=201908*,date=201808*}/*.parquet"
```
This should only read files belonging to August in 2018 and 2019.

Would this also work for you?

Best

**Comment by sergio-campos-corredera** [comment]
Hi @morazow,
I've tried to use braces {} in my expression regular and it didn't work:

```sql
IMPORT INTO TRADING_ANALYTICS.STG_US_ECOM_DTA_MPI
FROM SCRIPT ETL.IMPORT_PATH WITH
BUCKET_PATH    = 's3a://bucket/{year=2019/month=1,year=2019/month=2}/*'
DATA_FORMAT    = 'PARQUET'
S3_ACCESS_KEY  = 'XXXXX'
S3_SECRET_KEY  = 'XXX'
S3_ENDPOINT    = 's3-eu-west-1.amazonaws.com'
PARALLELISM    = 'nproc()';
```
I'm getting this error:
```
java.net.URISyntaxException: Illegal character in path at index 13: s3a://bucket/{year=2019/month=1,year=2019/month=2}/*
````
I'm using version 0.4.2, do you know if this feature was released in newer versions?
Thanks in advance,
Sergio

**Comment by morazow** [comment]
Hey @sergio-campos-corredera ,

Good catch! Thanks for reporting it!

I looked into it and it is actually a bug in all versions. I am going to fix it now.

**Comment by morazow** [comment]
Hey @drumcircle , @sergio-campos-corredera ,

I merged the fix for the regex pattern, and release a new [pre-release version](https://github.com/exasol/cloud-storage-etl-udfs/releases/tag/v0.6.0-7-g451d30c-SNAPSHOT) that matches current git describe.

Please use this version for now in order to use the regex patterns on the bucket paths.

Thanks for your feedback and contributions!

**Comment by reitzig** [comment]
I read regexp, but the examples look more like shell-style globbing? @morazow, can you please clarify which this is about?

**Comment by morazow** [comment]
Hey @reitzig,

Yes, that is correct. It is more about globbing. You can find short description on [`globStatus`](https://hadoop.apache.org/docs/r2.8.2/api/org/apache/hadoop/fs/FileSystem.html#globStatus(org.apache.hadoop.fs.Path)) method.

**Comment by drumcircle** [comment]
Can you clarify how this scales?  Are you always looking through every file in an S3 bucket?  Grabbing everything after the first non-regex part and then post-filtering?  Excellent work!

**Comment by morazow** [comment]
Hey @drumcircle,

I use the library implementation from Hadoop common filesystem. I have looked into it long time ago, briefly checked it again. 

1. Do brace expansion, `/base/{a,b,c}/ -> List(/base/a/, /base/b/, /base/c/)`
2. Do recursive listing if the expanded path has wildcards, `?` or `*`. So if there is path like `/base/*/a/`, list the `/base/*` part.

Therefore, it only call the list only when necessary so that not to perform expensive rpc to the namenode, in traditional Hadoop setups. I guess, this still holds not to do HEAD or GET operations on blob storages such as S3.

For more details you can check the implementations below:
- [`globStatus`](https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L2068-L2075)
- [`Globber.glob`](https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/Globber.java#L197-L206)
- [`GlobFilter.accept`](https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/GlobFilter.java#L80-L82)
- [`GlobPattern.matches`](https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/GlobPattern.java#L66-L68)

The last one use [Google/re2j](https://github.com/google/re2j) for wildcard matching.

**Comment by morazow** [comment]
Hey all,

I am going to close this issue. Please open a new issue if there are more questions.
