### ISSUE TITLE
Expose progress information of IMPORT queries

### ISSUE THREAD

**Issue by reitzig** [exasol/cloud-storage-extension#68]
Currently, `IMPORT` queries are atomic; we don't get feedback until it is done.
Please provide and document ways to programmatically monitor `IMPORT` queries.

Related to #61.

### Rationale

`IMPORT` queries can run for quite a while. We're building a data pipeline with an Exasol instance as one target, and we've seen >1TB of data (in ~25k Parquet files on S3) which took ~1.5d to import.

Unfortunately, we don't seem to get _any_ feedback on how far along the query is. In terms of observability and monitoring, that's a big issue. We're currently in the process of migrating to importing small batches of files after each other, which I understand is not best practice with Exasol (?).

I understand there are logs _on_ the Exasol cluster, but we can not acces that (in production); we are purely users of Exasol, not admins. Therefore, we can not access those logs. (Or can we?)

**Comment by morazow** [comment]
Hello @reitzig,


Okay, I will try to reply couple options here. Then, later maybe put them into a documentation.

However, I am not sure if they are helpful for you, we can discuss it.

## Remote Logging

In this case, you start a log listener in another server. This server should be reachable from the Exasol nodes.

For example using `netcat`:

```
nc -lkp 3000
```

Or using the [`udf_output.py`](https://github.com/exasol/hadoop-etl-udfs/blob/master/tools/udf_debug.py):

```
python udf_output.py
```

With redirects to a file,

```
python udf_output.py 2>&1 | tee import_udf.log
```

This server will be listening on port `3000`. 

Then before running the import statements in the Exasol database, set the `SCRIPT_OUTPUT_ADDRESS` using alter session.

```sql
ALTER SESSION SET SCRIPT_OUTPUT_ADDRESS='<REMOTE_LOGGING_SERVER_IPv4>:3000';

--- Usual import/export statements.
```

I guess in production setting you can maybe set a such a server. On my tests, I usually use the license/management server.

This way you can observe the logs from the [import udf](https://github.com/exasol/cloud-storage-etl-udfs/blob/master/src/main/scala/com/exasol/cloudetl/scriptclasses/ImportFiles.scala#L25-L28), total number of files per vm or each imported file. Additionally, you can add more log lines to the code if required.

## Use PyExasol - Script Output

This is similar to above, you still need separate server that listens on a port. But now, use [PyExasol](https://github.com/badoo/pyexasol) to run the import statements and capture the [script output logs](https://github.com/badoo/pyexasol/blob/master/examples/24_script_output.py).

I have not tested this option. However, it may be useful if you are already in python ecosystem.

## Using Profiling Information

Here the idea is to regularly run SQL queries to obtain the profiling information. 

For example,

```sql 
SELECT * FROM EXA_DBA_PROFILE_RUNNING;
```

Or 

```sql
SELECT * FROM EXA_USER_PROFILE_RUNNING;
```

These two command will return currently running import/export (or other) commands with some other profiling information such as duration, out_rows or sql_text. The output from these can be used to detect whether the import has already finished or not.

I hope these are helpful in order to get progress information from running UDFs. Otherwise, I can ask around for other options.

**Comment by reitzig** [comment]
This comes late, but: thanks for the elaborate answer! Never got arount to digging into this, but my successors on the project might. :D

**Comment by morazow** [comment]
Hey @reitzig,

Thanks for your feedback and contributions!

Please feel free to direct them to us :))
